#!/usr/bin/python2.7
# -*-coding:Latin-1 -*

# Import libs for ephemerides
from datetime import datetime, timedelta
import ANLib

# Init default values

# Prepare objects for computing ephemeris
theParameters = ANLib.Parameters() # read parameters file parameters_run.json
sParamDate = (datetime.now()).strftime("%Y%m%d")  # start date from current date at 00:00 + delta hours
sParamTime = "200000"
theCalendar = ANLib.Calendar(sParamDate,sParamTime)

# Compute ephemeris and produce new HTML
oMeeusAlgorithm = ANLib.MeeusAlgorithms(sParamDate,sParamTime)

# Display result
print ""
print ""
print "Date: " + theCalendar.getFormattedDateForSlot(0, theParameters.getDisplayNumberOfMinutesPerSlot()) + " " + theCalendar.getTimeForSlotAsHHMM(0, theParameters.getDisplayNumberOfMinutesPerSlot()) + " GMT        (JD: " + str(theCalendar.getJulianDate()) + ", " + str('{:0.2f}'.format(theCalendar.getDateValueForTimeSlot(0, theParameters.getDisplayNumberOfMinutesPerSlot()))) + " jours depuis le 01/01/2000)"
print "Lieu: " + (theParameters.getPlace().getName() + " "*25)[0:25] + "(Long: " + ANLib.CommonAstroFormulaes.getDMSFromDeg(theParameters.getPlace().getLongitude()) + ", Lat: " + ANLib.CommonAstroFormulaes.getDMSFromDeg(theParameters.getPlace().getLatitude()) + ")"
print ""
print "Astre        Asc. Droite      Declinaison     Azimut     Altitude    Distance (km)    Diam. App.     Phase    Illum.   Sel lon   Sel lat   Colong"
print "-------------------------------------------------------------------------------------------------------------------------------------------------"
print "Soleil     " + ('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(oMeeusAlgorithm.getRightAscension('Sun')))[-13:]     + "    " + ('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(oMeeusAlgorithm.getDeclination('Sun')))[-13:]     + "  " + ('          ' + '{:0.4f}'.format(oMeeusAlgorithm.getAzimut('Sun', theParameters.getPlace().getLongitude(), theParameters.getPlace().getLatitude())))[-9:]     + "    " + ('          ' + '{:0.4f}'.format(oMeeusAlgorithm.getElevation('Sun', theParameters.getPlace().getLongitude(), theParameters.getPlace().getLatitude())))[-9:] + (" "*17 + '{:0.0f}'.format(oMeeusAlgorithm.getDistanceInKm('Sun')))[-17:]      + " "*14  + " "*10  + " "*10
print ""
print "Lune       " + ('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(oMeeusAlgorithm.getRightAscension('Moon')))[-13:]    + "    " + ('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(oMeeusAlgorithm.getDeclination('Moon')))[-13:]    + "  " + ('          ' + '{:0.4f}'.format(oMeeusAlgorithm.getAzimut('Moon', theParameters.getPlace().getLongitude(), theParameters.getPlace().getLatitude())))[-9:]    + "    " + ('          ' + '{:0.4f}'.format(oMeeusAlgorithm.getElevation('Moon', theParameters.getPlace().getLongitude(), theParameters.getPlace().getLatitude())))[-9:]    + "       " + ('           ' + '{:0.0f}'.format(oMeeusAlgorithm.getDistanceInKm('Moon')))[-10:]      + "                " + ('        ' + '{:0.3f}'.format(oMeeusAlgorithm.getPhaseAngle('Moon')))[-8:]      + "   " + ('     ' + '{:0.2f}'.format(100 * oMeeusAlgorithm.getIllumination('Moon')))[-6:] + "%"  + "   " + ('     ' + '{:0.2f}'.format(oMeeusAlgorithm.getSubSolarSelenographicLongitude('Moon')))[-7:]   + "   " + ('     ' + '{:0.2f}'.format(oMeeusAlgorithm.getSubSolarSelenographicLatitude('Moon')))[-7:]   + "   " + ('     ' + '{:0.2f}'.format(oMeeusAlgorithm.getSelenographicColongitude('Moon')))[-6:] 
print ""
#print "Mercure    " + str('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(theEphemeridesData.getEphemerideDataObject("Mercury").getRightAscensionForSlot(0)))[-13:] + "    " + str('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(theEphemeridesData.getEphemerideDataObject("Mercury").getDeclinationForSlot(0)))[-13:] + "  " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Mercury").getAzimutForSlot(0)))[-9:] + "    " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Mercury").getAltitudeForSlot(0)))[-9:] + "       " + str('           ' + '{:0.0f}'.format(ANLib.CommonAstroFormulaes.ConvertUAToKM(theEphemeridesData.getEphemerideDataObject("Mercury").getDistanceForSlot(0))))[-10:] + "     " + str('         ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Mercury").getApparentDiameterInArcSecForSlot(0)))[-8:]
#print "Venus      " + str('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(theEphemeridesData.getEphemerideDataObject("Venus").getRightAscensionForSlot(0)))[-13:]   + "    " + str('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(theEphemeridesData.getEphemerideDataObject("Venus").getDeclinationForSlot(0)))[-13:]   + "  " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Venus").getAzimutForSlot(0)))[-9:]   + "    " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Venus").getAltitudeForSlot(0)))[-9:]   + "       " + str('           ' + '{:0.0f}'.format(ANLib.CommonAstroFormulaes.ConvertUAToKM(theEphemeridesData.getEphemerideDataObject("Venus").getDistanceForSlot(0))))[-10:]   + "     " + str('         ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Venus").getApparentDiameterInArcSecForSlot(0)))[-8:]
#print "Mars       " + str('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(theEphemeridesData.getEphemerideDataObject("Mars").getRightAscensionForSlot(0)))[-13:]    + "    " + str('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(theEphemeridesData.getEphemerideDataObject("Mars").getDeclinationForSlot(0)))[-13:]    + "  " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Mars").getAzimutForSlot(0)))[-9:]    + "    " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Mars").getAltitudeForSlot(0)))[-9:]    + "       " + str('           ' + '{:0.0f}'.format(ANLib.CommonAstroFormulaes.ConvertUAToKM(theEphemeridesData.getEphemerideDataObject("Mars").getDistanceForSlot(0))))[-10:]    + "     " + str('         ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Mars").getApparentDiameterInArcSecForSlot(0)))[-8:]
#print "Jupiter    " + str('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(theEphemeridesData.getEphemerideDataObject("Jupiter").getRightAscensionForSlot(0)))[-13:] + "    " + str('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(theEphemeridesData.getEphemerideDataObject("Jupiter").getDeclinationForSlot(0)))[-13:] + "  " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Jupiter").getAzimutForSlot(0)))[-9:] + "    " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Jupiter").getAltitudeForSlot(0)))[-9:] + "       " + str('           ' + '{:0.0f}'.format(ANLib.CommonAstroFormulaes.ConvertUAToKM(theEphemeridesData.getEphemerideDataObject("Jupiter").getDistanceForSlot(0))))[-10:] + "     " + str('         ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Jupiter").getApparentDiameterInArcSecForSlot(0)))[-8:]
#print "Saturne    " + str('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(theEphemeridesData.getEphemerideDataObject("Saturn").getRightAscensionForSlot(0)))[-13:]  + "    " + str('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(theEphemeridesData.getEphemerideDataObject("Saturn").getDeclinationForSlot(0)))[-13:]  + "  " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Saturn").getAzimutForSlot(0)))[-9:]  + "    " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Saturn").getAltitudeForSlot(0)))[-9:]  + "       " + str('           ' + '{:0.0f}'.format(ANLib.CommonAstroFormulaes.ConvertUAToKM(theEphemeridesData.getEphemerideDataObject("Saturn").getDistanceForSlot(0))))[-10:]  + "     " + str('         ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Saturn").getApparentDiameterInArcSecForSlot(0)))[-8:]
#print "Uranus     " + str('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(theEphemeridesData.getEphemerideDataObject("Uranus").getRightAscensionForSlot(0)))[-13:]  + "    " + str('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(theEphemeridesData.getEphemerideDataObject("Uranus").getDeclinationForSlot(0)))[-13:]  + "  " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Uranus").getAzimutForSlot(0)))[-9:]  + "    " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Uranus").getAltitudeForSlot(0)))[-9:]  + "       " + str('           ' + '{:0.0f}'.format(ANLib.CommonAstroFormulaes.ConvertUAToKM(theEphemeridesData.getEphemerideDataObject("Uranus").getDistanceForSlot(0))))[-10:]  + "     " + str('         ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Uranus").getApparentDiameterInArcSecForSlot(0)))[-8:]
#print "Neptune    " + str('              ' + ANLib.CommonAstroFormulaes.getHMSFromDeg(theEphemeridesData.getEphemerideDataObject("Neptune").getRightAscensionForSlot(0)))[-13:] + "    " + str('              ' + ANLib.CommonAstroFormulaes.getDMSFromDeg(theEphemeridesData.getEphemerideDataObject("Neptune").getDeclinationForSlot(0)))[-13:] + "  " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Neptune").getAzimutForSlot(0)))[-9:] + "    " + str('          ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Neptune").getAltitudeForSlot(0)))[-9:] + "       " + str('           ' + '{:0.0f}'.format(ANLib.CommonAstroFormulaes.ConvertUAToKM(theEphemeridesData.getEphemerideDataObject("Neptune").getDistanceForSlot(0))))[-10:] + "     " + str('         ' + '{:0.4f}'.format(theEphemeridesData.getEphemerideDataObject("Neptune").getApparentDiameterInArcSecForSlot(0)))[-8:]
print ""
print ""
